[project]
name = "ps-dist"
license = {file = "LICENSE"}
readme = "README.md"
authors = [
    {name = "Austin Hoover", email = "austin.michael.hoover@gmail.com"}
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
   "h5py",
   "ipywidgets",
   "matplotlib==3.8.4",
   "numpy",
   "proplot @ git+https://github.com/austin-hoover/proplot@82e1d9c169c73832ee3c917585f4e30a4d378e22",
   "scipy",
   "tqdm",
]

[project.urls]
"Source Code" = "https://github.com/austin-hoover/ps-dist"

[build-system]
requires = [
    "setuptools>=62",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "psdist/_version.py"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 110
target-version = ["py39"]